export default [
  {
    id: "1",
    company: 'adidas',
    name: "Matchcourt shoes",
    collection: "Men's Originals",
    description: "Inspired by classic adidas court footwear, these shoes are redesigned specifically for skateboarding. The soft suede upper and durable rubber outsole hold up to regular sessions. A textile lining and molded sockliner ensure supreme comfort on or off the board.",
    price: "70",
    image1: "upload/1-1.webp",
    image2: "upload/1-2.webp",
    image3: "upload/1-3.webp",
    image4: "upload/1-4.webp",
    image5: "upload/1-5.webp",
  },
  {
    id: "2",
    company: 'adidas',
    name: "City Cup shoes",
    collection: "Men's Originals",
    description: "Designed with a unique double-cup midsole, these skate shoes will stand up to even your most intense park or street sessions. They feature a nubuck and nylon upper and a rubber outsole for optimal support. A breathable mesh lining provides all-day comfort, and the reinforced toe and heel help resist blowouts.",
    price: "80",
    image1: "upload/2-1.webp",
    image2: "upload/2-2.webp",
    image3: "upload/2-3.webp",
    image4: "upload/2-4.webp",
    image5: "upload/2-5.webp",
  },
  {
    id: "3",
    company: 'dc',
    name: "Crisis",
    collection: "",
    description: "",
    price: "65",
    image1: "upload/3-1.jpg",
    image2: "upload/3-2.jpg",
    image3: "upload/3-3.jpg",
    image4: "upload/3-4.jpg",
    image5: "upload/3-5.jpg",
  },
  {
    id: "4",
    company: 'adidas',
    name: "Matchcourt shoes",
    collection: "Men's Originals",
    description: "Inspired by classic adidas court footwear, these shoes are redesigned specifically for skateboarding. The soft suede upper and durable rubber outsole hold up to regular sessions. A textile lining and molded sockliner ensure supreme comfort on or off the board.",
    price: "70",
    image1: "upload/1-1.webp",
    image2: "upload/1-2.webp",
    image3: "upload/1-3.webp",
    image4: "upload/1-4.webp",
    image5: "upload/1-5.webp",
  },
  {
    id: "5",
    company: 'adidas',
    name: "Matchcourt shoes",
    collection: "Men's Originals",
    description: "Inspired by classic adidas court footwear, these shoes are redesigned specifically for skateboarding. The soft suede upper and durable rubber outsole hold up to regular sessions. A textile lining and molded sockliner ensure supreme comfort on or off the board.",
    price: "70",
    image1: "upload/1-1.webp",
    image2: "upload/1-2.webp",
    image3: "upload/1-3.webp",
    image4: "upload/1-4.webp",
    image5: "upload/1-5.webp",
  },
  {
    id: "6",
    company: 'adidas',
    name: "Matchcourt shoes",
    collection: "Men's Originals",
    description: "Inspired by classic adidas court footwear, these shoes are redesigned specifically for skateboarding. The soft suede upper and durable rubber outsole hold up to regular sessions. A textile lining and molded sockliner ensure supreme comfort on or off the board.",
    price: "70",
    image1: "upload/1-1.webp",
    image2: "upload/1-2.webp",
    image3: "upload/1-3.webp",
    image4: "upload/1-4.webp",
    image5: "upload/1-5.webp",
  },
  {
    id: "7",
    company: 'adidas',
    name: "Matchcourt shoes",
    collection: "Men's Originals",
    description: "Inspired by classic adidas court footwear, these shoes are redesigned specifically for skateboarding. The soft suede upper and durable rubber outsole hold up to regular sessions. A textile lining and molded sockliner ensure supreme comfort on or off the board.",
    price: "70",
    image1: "upload/1-1.webp",
    image2: "upload/1-2.webp",
    image3: "upload/1-3.webp",
    image4: "upload/1-4.webp",
    image5: "upload/1-5.webp",
  },
]