export default [
  {
    id: "1",
    company: 'adidas',
    name: "Matchcourt shoes",
    collection: "Men's Originals",
    description: "Inspired by classic adidas court footwear, these shoes are redesigned specifically for skateboarding. The soft suede upper and durable rubber outsole hold up to regular sessions. A textile lining and molded sockliner ensure supreme comfort on or off the board.",
    price: "70",
    image1: "upload/1-1.webp",
    image2: "upload/1-2.webp",
    image3: "upload/1-3.webp",
    image4: "upload/1-4.webp",
    image5: "upload/1-5.webp",
  },
  {
    id: "2",
    company: 'adidas',
    name: "City Cup shoes",
    collection: "Men's Originals",
    description: "Designed with a unique double-cup midsole, these skate shoes will stand up to even your most intense park or street sessions. They feature a nubuck and nylon upper and a rubber outsole for optimal support. A breathable mesh lining provides all-day comfort, and the reinforced toe and heel help resist blowouts.",
    price: "80",
    image1: "upload/2-1.webp",
    image2: "upload/2-2.webp",
    image3: "upload/2-3.webp",
    image4: "upload/2-4.webp",
    image5: "upload/2-5.webp",
  },
  {
    id: "3",
    company: 'dc shoes',
    name: "Crisis",
    collection: "Infinite shoes",
    description: "Suede or leather upper [depending on colorway. Rubber toe cap for a longer lasting skateboarding shoe. Foam padded tongue and collar for added comfort and support. Vulcanized tread construction for great board-feel and sole flex",
    price: "65",
    image1: "upload/3-1.jpg",
    image2: "upload/3-2.jpg",
    image3: "upload/3-3.jpg",
    image4: "upload/3-4.jpg",
    image5: "upload/3-5.jpg",
  },
  {
    id: "4",
    company: 'adidas',
    name: "Busenitz shoes",
    collection: "Men's Originals",
    description: "The Busenitz takes style cues from the legendary adidas Copa Mundial, the pro rider's favorite football boots back in the day. These skate shoes are built for speed and precision, with a slim cupsole that made waves when the signature model first dropped in 2006. This version keeps it classic with a durable suede upper, an oversize tongue and padded collar.",
    price: "80",
    image1: "upload/6-1.webp",
    image2: "upload/6-2.webp",
    image3: "upload/6-3.webp",
    image4: "upload/6-4.webp",
    image5: "upload/6-5.webp",
  },
  {
    id: "5",
    company: 'adidas',
    name: "Campus adv shoes",
    collection: "Originals",
    description: "Inspired by the original '80s-era Campus low tops, these shoes reimagine a classic look for skateboarding. They feature a durable leather upper and have a rubber outsole for optimal support. Bounce cushioning in the midsole provides energized comfort for when your skate sessions kick into overdrive.",
    price: "80",
    image1: "upload/7-1.webp",
    image2: "upload/7-2.webp",
    image3: "upload/7-3.webp",
    image4: "upload/7-4.webp",
    image5: "upload/7-5.webp",
  },
  {
    id: "6",
    company: 'adidas',
    name: "Sabalo X hardies",
    collection: "Men's Originals",
    description: "Designed with input from ripper Tyshawn Jones and Hardies Hardware, these shoes reference the fisheye lens used to capture skateboarding's timeless imagery. These shoes feature a flexible sole and a leather upper layered over a snug, sock-like liner. A durable rubber outsole provides superior grip and board feel.",
    price: "80",
    image1: "upload/8-1.webp",
    image2: "upload/8-2.webp",
    image3: "upload/8-3.webp",
    image4: "upload/8-4.webp",
    image5: "upload/8-5.webp",
  },
  {
    id: "7",
    company: 'nike',
    name: "Nike SB Zoom Mid RM",
    collection: "Skate Shoe",
    description: "The Nike SB Zoom Stefan Janoski Mid RM pairs a minimal look with a modern fit. It has been updated with a new, plush sockliner and a flexible midsole for better boardfeel right out of the box.",
    price: "95",
    image1: "upload/5-1.webp",
    image2: "upload/5-2.webp",
    image3: "upload/5-3.webp",
    image4: "upload/5-4.webp",
    image5: "upload/5-5.webp",
  },
  {
    id: "8",
    company: 'nike',
    name: "Nike SB Zoom RM Crafted",
    collection: "Skate Shoe",
    description: "The Nike SB Zoom Stefan Janoski RM Crafted celebrates Stefan's contributions to the worlds of skate and art. Handwoven leather gives you a unique look while refined cushioning and flexible rubber optimize your performance.",
    price: "100",
    image1: "upload/4-1.webp",
    image2: "upload/4-2.webp",
    image3: "upload/4-3.webp",
    image4: "upload/4-4.webp",
    image5: "upload/4-5.webp",
  },
]